### ISSUE TITLE
Can't get past Stage 1

### ISSUE THREAD

**Issue by bherr2** [andreasbueckle/ccf-organ-vr-gallery#11]
When I enter the app, I see the female body and 3 orbs (1 for each stage), but I'm not able to select anything or move around really. I may be missing some detail here. There used to be some beams that came from the controller that you could select stuff but it's not showing.

**Comment by andreasbueckle** [comment]
@bherr2 
You need to touch the three balls with your controller to go to the next stage. We did not implement selector rays here yet, but may add them in the future.

**Comment by bherr2** [comment]
Ahh, ok, I was finally able to touch one of the balls (they seem to almost always be outside of the guardian grid). once I'm on to stage two I can select an organ, but exploding doesn't seem to work when I move the right joystick up and down. Stage three, the things are still pretty far out of the guardian grid.

**Comment by andreasbueckle** [comment]
Thanks, Positioning is still an issue. Will revisit for v. 0.4.2.
